apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sharukesh/anokha2026-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: QDRANT_URL
              value: http://qdrant:6333
            - name: OLLAMA_BASE_URL
              value: http://ollama:11434
            - name: POSTGRES_URI
              value: postgresql://user:password@postgres:5432/career_guide
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"

apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
